deploy:
  stage: deploy
  script:
    - puma-stop 5000
    - mkdir -p ~/project
    - rsync -ar --delete . ~/project
    - cd ~/project
    - bundle install
    - yarn install
    - rails db:migrate
    - nohup rails server -d -b 0.0.0.0 -p 5000 &
  only:
    - project
